name: Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Node.js environment to run tests
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test
        env:
          # Provide environment variables from GitHub Secrets
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
          MY_GMAIL_ID: ${{ secrets.MY_GMAIL_ID }}
          MY_GMAIL_PASSWORD: ${{ secrets.MY_GMAIL_PASSWORD }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: test-and-build # Ensures this job runs only after tests pass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t kamit6337/voosh-project-server:latest .

      - name: Push the Docker image to Docker Hub
        run: docker push kamit6337/voosh-project-server:latest
